./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
./userapp & > ./logfile.txt        
